
extern int num_q;
extern int num_atom;
extern int num_ele;
extern float k_chi;
extern float q_S_ref_dS[903];
//extern float q[301];
//extern float S_ref[301];
//extern float dS[301];
//extern float FF[2668];
/*extern float q[667];
extern float S_ref[667];
extern float dS[667];
extern float FF[2668];*/
extern int Ele[1749];
extern int num_q2;
extern int num_atom2;
extern int num_pp;
extern int bond_pp[42];
extern int num_raster; 
extern int num_raster2;
extern float sol_s;
extern float vdW[6];
